FROM golang:1.20 as builder

WORKDIR /usr/src/project

COPY . .

RUN go build -o ./build/server ./cmd/server/main.go

FROM ubuntu:22.04

WORKDIR /usr/bin

RUN apt-get update && \
    apt-get install -y ca-certificates

COPY --from=builder /usr/src/project/build/server ./server

ENTRYPOINT [ "./server" ]
